blank_issues_enabled: false
contact_links:
  - name: Support / Help / Questions
    url: https://github.com/gatsby-uc/plugins/discussions/new?category=q-a
    about: Having trouble configuring/using a plugin or just have a question? Open a discussion!
  - name: Community
    url: https://discord.gg/GwNqFzeTJv
    about: Join our Discord!
